const statusMap = {
  'Pending Verification': 'warning',
  'Pending Review': 'warning',
  'Under Review': 'warning',
  'Pending Approval': 'warning',
  Pending: 'warning',
  Planning: 'info',
  Preparing: 'info',
  Scheduled: 'info',
  'In Progress': 'info',
  'In Transit': 'info',
  Delivered: 'success',
  'To Do': 'neutral',
  'In Review': 'warning',
  Done: 'success',
  Verified: 'success',
  Approved: 'success',
  Active: 'success',
  Available: 'success',
  Completed: 'success',
  Generated: 'success',
  Received: 'success',
  'Awaiting Confirmation': 'warning',
  'Not Received': 'danger',
  Disputed: 'danger',
  Rejected: 'danger',
  'Proof Rejected': 'danger',
  'Proof Submitted': 'warning',
  'Proof Verified': 'success',
  'Awaiting Proof': 'warning',
  Distributed: 'neutral',
  Allocated: 'neutral',
  Assigned: 'neutral',
  Reserved: 'neutral',
  'In Inventory': 'neutral',
  'Low Stock': 'danger',
  High: 'danger',
  Medium: 'warning',
  Low: 'info',
}
export default function StatusBadge({ status }) {
  const variant = statusMap[status] || 'neutral'
  return <span className={`status-badge status-badge--${variant}`}>{status}</span>
}
