-- ============================================================
-- Rise Above Foundation — FULL DATABASE SCHEMA
-- Database: donation_system
-- Run in phpMyAdmin → SQL tab (Step 1)
-- ============================================================

CREATE DATABASE IF NOT EXISTS donation_system
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_general_ci;

USE donation_system;

-- ---------- AUTH (login) ----------
CREATE TABLE IF NOT EXISTS roles (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO roles (name) VALUES ('Admin'), ('Staff'), ('Donor'), ('Volunteer'), ('Beneficiary');

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  role_id INT UNSIGNED NOT NULL,
  full_name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  status ENUM('ACTIVE','PENDING','DISABLED') NOT NULL DEFAULT 'ACTIVE',
  email_verified_at TIMESTAMP NULL,
  verification_token VARCHAR(64) NULL,
  verification_sent_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_users_role_id FOREIGN KEY (role_id) REFERENCES roles(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------- DONORS ----------
CREATE TABLE IF NOT EXISTS donors (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NULL,
  code VARCHAR(20) NOT NULL UNIQUE,
  full_name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NULL,
  phone VARCHAR(40) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_donors_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------- DONATIONS ----------
CREATE TABLE IF NOT EXISTS donations (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tracking_code VARCHAR(20) NOT NULL UNIQUE,
  donor_id BIGINT UNSIGNED NULL,
  donor_name VARCHAR(120) NOT NULL,
  donor_email VARCHAR(190) NULL,
  type ENUM('Monetary','In-Kind') NOT NULL DEFAULT 'Monetary',
  category VARCHAR(60) NULL,
  amount DECIMAL(12,2) NULL,
  items_description VARCHAR(255) NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'Pending Verification',
  donation_date DATE NOT NULL,
  notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_donations_donor_id FOREIGN KEY (donor_id) REFERENCES donors(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------- BENEFICIARIES ----------
CREATE TABLE IF NOT EXISTS beneficiaries (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NULL,
  code VARCHAR(20) NOT NULL UNIQUE,
  full_name VARCHAR(120) NOT NULL,
  category VARCHAR(80) NULL,
  barangay_type VARCHAR(60) NULL,
  barangay VARCHAR(80) NULL,
  municipality VARCHAR(80) NULL,
  address VARCHAR(255) NULL,
  affected_families INT UNSIGNED NOT NULL DEFAULT 0,
  representative_name VARCHAR(120) NULL,
  representative_phone VARCHAR(40) NULL,
  representative_email VARCHAR(190) NULL,
  needs TEXT NULL,
  notes TEXT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'Pending Approval',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_beneficiaries_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------- ASSISTANCE REQUESTS ----------
CREATE TABLE IF NOT EXISTS assistance_requests (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  reference_code VARCHAR(20) NOT NULL UNIQUE,
  beneficiary_id BIGINT UNSIGNED NOT NULL,
  assistance_type VARCHAR(80) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'Pending Review',
  priority ENUM('Low','Medium','High') NOT NULL DEFAULT 'Medium',
  request_date DATE NOT NULL,
  notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_assistance_beneficiary_id FOREIGN KEY (beneficiary_id) REFERENCES beneficiaries(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------- INVENTORY ----------
CREATE TABLE IF NOT EXISTS inventory_items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(20) NOT NULL UNIQUE,
  item_name VARCHAR(120) NOT NULL,
  category VARCHAR(60) NULL,
  quantity INT UNSIGNED NOT NULL DEFAULT 0,
  unit VARCHAR(30) NOT NULL DEFAULT 'units',
  low_stock_threshold INT UNSIGNED NOT NULL DEFAULT 100,
  allocated INT UNSIGNED NOT NULL DEFAULT 0,
  distributed INT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------- REPACKING ----------
CREATE TABLE IF NOT EXISTS repacking_jobs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(20) NOT NULL UNIQUE,
  source_item_id BIGINT UNSIGNED NULL,
  source_items VARCHAR(120) NOT NULL,
  source_quantity INT UNSIGNED NOT NULL DEFAULT 0,
  output_item VARCHAR(120) NOT NULL,
  output_unit VARCHAR(30) NULL,
  quantity INT UNSIGNED NOT NULL DEFAULT 0,
  status VARCHAR(50) NOT NULL DEFAULT 'Scheduled',
  assigned_to VARCHAR(120) NULL,
  due_date DATE NULL,
  notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------- ALLOCATIONS ----------
CREATE TABLE IF NOT EXISTS allocations (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(20) NOT NULL UNIQUE,
  resource_name VARCHAR(120) NOT NULL,
  quantity INT UNSIGNED NOT NULL DEFAULT 0,
  program VARCHAR(80) NULL,
  beneficiary_target VARCHAR(120) NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'Pending',
  allocation_date DATE NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------- DISTRIBUTIONS ----------
CREATE TABLE IF NOT EXISTS distributions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(20) NOT NULL UNIQUE,
  event_name VARCHAR(160) NULL,
  location VARCHAR(120) NOT NULL,
  beneficiary_id BIGINT UNSIGNED NULL,
  items_summary TEXT NULL,
  coordinator VARCHAR(120) NULL,
  notes TEXT NULL,
  program VARCHAR(80) NULL,
  distribution_date DATE NULL,
  schedule_time VARCHAR(20) NULL,
  beneficiaries_count INT UNSIGNED NOT NULL DEFAULT 0,
  volunteers_count INT UNSIGNED NOT NULL DEFAULT 0,
  vehicles_count INT UNSIGNED NOT NULL DEFAULT 0,
  distance_km DECIMAL(7,1) NULL,
  fuel_liters DECIMAL(8,2) NULL,
  fuel_cost DECIMAL(10,2) NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'Planning',
  distribution_type VARCHAR(50) NOT NULL DEFAULT 'Delivery',
  proof_status ENUM('Not Required','Awaiting Proof','Proof Submitted','Proof Verified') NOT NULL DEFAULT 'Not Required',
  receipt_status VARCHAR(40) NOT NULL DEFAULT 'Awaiting Confirmation',
  received_quantity INT UNSIGNED NULL,
  received_at TIMESTAMP NULL,
  receipt_notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------- VOLUNTEERS ----------
CREATE TABLE IF NOT EXISTS volunteers (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NULL,
  code VARCHAR(20) NOT NULL UNIQUE,
  full_name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NULL,
  programs_json TEXT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'Pending Review',
  hours INT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_volunteers_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------- VOLUNTEER SCHEDULE ----------
CREATE TABLE IF NOT EXISTS volunteer_schedule (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  volunteer_id BIGINT UNSIGNED NOT NULL,
  event_date DATE NOT NULL,
  event_title VARCHAR(200) NOT NULL,
  event_time VARCHAR(30) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_schedule_volunteer_id FOREIGN KEY (volunteer_id) REFERENCES volunteers(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------- TASKS ----------
CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(20) NOT NULL UNIQUE,
  title VARCHAR(200) NOT NULL,
  assignee VARCHAR(120) NULL,
  assignee_user_id BIGINT UNSIGNED NULL,
  priority VARCHAR(20) NOT NULL DEFAULT 'Medium',
  due_date DATE NULL,
  duty_start VARCHAR(10) NULL,
  duty_end VARCHAR(10) NULL,
  duty_hours DECIMAL(5,2) NULL,
  module VARCHAR(50) NULL,
  board_column ENUM('todo','inProgress','review','done') NOT NULL DEFAULT 'todo',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_tasks_assignee_user_id FOREIGN KEY (assignee_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------- CERTIFICATES ----------
CREATE TABLE IF NOT EXISTS certificates (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(20) NOT NULL UNIQUE,
  cert_type VARCHAR(80) NOT NULL,
  recipient_type VARCHAR(30) NOT NULL DEFAULT 'Donor',
  recipient_name VARCHAR(120) NOT NULL,
  reference_code VARCHAR(30) NULL,
  details TEXT NULL,
  signatory_name VARCHAR(120) NULL,
  signatory_title VARCHAR(120) NULL,
  cert_date DATE NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'Pending',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------- CMS: PROGRAMS ----------
CREATE TABLE IF NOT EXISTS programs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  description TEXT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------- CMS: ANNOUNCEMENTS ----------
CREATE TABLE IF NOT EXISTS announcements (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  category VARCHAR(80) NULL,
  excerpt TEXT NULL,
  published_date DATE NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------- CMS: PARTNERS ----------
CREATE TABLE IF NOT EXISTS partners (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  category VARCHAR(80) NULL,
  description TEXT NULL,
  website VARCHAR(255) NULL,
  initials VARCHAR(10) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------- CMS: SUCCESS STORIES ----------
CREATE TABLE IF NOT EXISTS success_stories (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  category VARCHAR(80) NULL,
  excerpt TEXT NULL,
  content TEXT NULL,
  testimonial TEXT NULL,
  story_date DATE NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------- NOTIFICATIONS ----------
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NULL,
  role_target VARCHAR(50) NULL,
  type VARCHAR(50) NOT NULL,
  title VARCHAR(200) NOT NULL,
  message TEXT NOT NULL,
  link VARCHAR(255) NULL,
  is_read TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_notifications_user (user_id, is_read),
  INDEX idx_notifications_role (role_target, is_read),
  CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------- DISTRIBUTION PROOFS ----------
CREATE TABLE IF NOT EXISTS distribution_proofs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  distribution_id BIGINT UNSIGNED NOT NULL,
  beneficiary_id BIGINT UNSIGNED NOT NULL,
  submitted_by_user_id BIGINT UNSIGNED NULL,
  file_path VARCHAR(255) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  file_type VARCHAR(80) NULL,
  notes TEXT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'Pending',
  review_remarks TEXT NULL,
  reviewed_by_user_id BIGINT UNSIGNED NULL,
  submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reviewed_at TIMESTAMP NULL,
  CONSTRAINT fk_proof_distribution FOREIGN KEY (distribution_id) REFERENCES distributions(id) ON DELETE CASCADE,
  CONSTRAINT fk_proof_beneficiary FOREIGN KEY (beneficiary_id) REFERENCES beneficiaries(id) ON DELETE CASCADE,
  CONSTRAINT fk_proof_user FOREIGN KEY (submitted_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
